const defaultPortrait = '/static/image/portrait.png';
const defaultAvatar = 'https://thirdwx.qlogo.cn/mmopen/vi_32/POgEwh4mIHO4nibH0KlMECNjjGxQUq24ZEaGT4poC6icRiccVGKSyXwibcPq4BWmiaIGuG1icwxaQX6grC9VemZoJ8rg/132'
const defaultOcrFront = '/static/image/idcard_front.png'
const defaultOcrBack = '/static/image/idcard_back.png'

const DLS = "加载中"
const DLD = "2022-06-06 00:00:00"
const LOAD = '加载中'
const defaultRouteDetail = {
  areaCode: LOAD,
  down: {
    endStation: LOAD,
    geometry: '',
    id: '3309002281',
    startFirst: LOAD,
    startLast: LOAD,
    startStation: LOAD,
    stationList: [],
  },
  lineName: '加载中',
  up: {
    endStation: LOAD,
    geometry: '',
    id: '3309002281',
    startFirst: LOAD,
    startLast: LOAD,
    startStation: LOAD,
    stationList: [],
  },
}
module.exports = {
  DLS,
  DLD,
  defaultPortrait,
  defaultAvatar,
  defaultOcrFront,
  defaultOcrBack,
  // videoRateList: [1.0, 1.25, 1.5, 2.0],
  videoRateList: [1.0, 1.25, 1.5],
  initUserInfo: {
    avatar: defaultAvatar,
    nickName: "微信名",
    name: "未登录",
    idcard: '',
    portrait: '',
    ocrFront: '',
    ocrBack: '',
    status: '1'
  },
  initClassInfo: {
    categoryId: "",
    certificateId: null,
    coverUrl: "https://asqz.obs.cn-east-2.myhuaweicloud.com/e7ec061f7747404b9c1780f210c5917a.jpeg",
    createTime: DLD,
    enterEndTime: DLD,
    enterStartTime: DLD,
    headTeacher: DLS,
    id: "",
    isOnline: "2",
    isPublic: "2",
    isFree: "2",
    mode: "1",
    name: DLS,
    planId: "",
    price: 0,
    status: "1",
    trainEndTime: DLD,
    trainStartTime: DLD,
    type: "1",
    updateTime: DLD,
    courseNum: 0,
    chapterNum: 0,
    classesTime: 0,
    time: 0,
    studentNum: 0,
    content: '加载中',
    remark: '加载中',
  },
  initGoodsInfo: {
    "goodsOrderId": "",
    "goodsId": "",
    "goodsName": DLS,
    "amount": "0.00",
    "userId": "",
    "status": "0",
    "payOrderId": null,
    "createTime": DLD,
    "updateTime": DLD,
    "delFlag": "0",
    "tenantId": null,
    "shopClasses": {
      "id": "",
      "name": DLS,
      "planId": "",
      "categoryId": "",
      "mode": "1",
      "type": "3",
      "createBy": "",
      "updateBy": "",
      "createTime": DLD,
      "updateTime": DLD,
      "delFlag": "0",
      "tenantId": null,
      "trainStartTime": DLD,
      "trainEndTime": DLD,
      "enterStartTime": DLD,
      "enterEndTime": DLD,
      "status": "3",
      "coverUrl": "https://asqz.obs.cn-east-2.myhuaweicloud.com/fadcb653637540918ed2f99d58909066.jpeg",
      "headTeacher": "",
      "price": 0.00,
      "isPublic": "2",
      "isOnline": "2",
      "certificateId": null
    }
  },
  initFormInfo: {
    categoryName: DLS,
    classesId: "",
    classesName: DLS,
    coverUrl: "https://asqz.obs.cn-east-2.myhuaweicloud.com/fadcb653637540918ed2f99d58909066.jpeg",
    enterEndTime: DLD,
    enterStartTime: DLD,
    goodsOrderId: "",
    headTeacher: "",
    id: "",
    payStatus: "0",
    price: 0,
    status: "2",
    submitTime: DLD,
    trainEndTime: DLD,
    trainStartTime: DLD,
    type: "3",
    userId: "",
  },
  initCourseInfo: {
    chapterNum: 0,
    children: [],
    classesTime: 0,
    coverUrl: "",
    name: DLS,
    time: 0,
    videoNum: 0,
  },
  initVideoInfo: {
    chapterId: "",
    coverUrl: "",
    createBy: "",
    createTime: DLD,
    delFlag: "0",
    finishTime: 0,
    finishMinuteTime: 0,
    id: "",
    materialId: "",
    name: DLS,
    sort: 1,
    status: null,
    teacherId: "1",
    teacherName: "null",
    tenantId: null,
    time: 0,
    updateBy: " ",
    updateTime: DLD,
    url: '',
  },
  initQuestion: {
    "id": "",
    "name": DLS,
    "type": "1",
    "parse": DLS,
    "answer": "B",
    "answers": null,
    "questionNum": null,
    "answerArray": [],
    "optionArray": [],
    "status": null,
    "isRight": null,
    "rightCount": 0,
    "errorCount": 0
  },
  typeOption: [
    { text: '全部', value: '0' },
    { text: '初训', value: '1' },
    { text: '复训', value: '2' },
    { text: '换证', value: '3' },
    { text: '再培训', value: '4' },
  ],
  initBannerList: [
    [
      {
        "id": "",
        "name": DLS,
        "mode": "1",
        "type": "1",
        "trainStartTime": DLD,
        "trainEndTime": DLD,
        "enterStartTime": DLD,
        "enterEndTime": DLD,
        "status": "2",
        "coverUrl": "",
        "headTeacher": DLS,
        "price": 0.00,
        "isPublic": "2",
        "isOnline": "2",
        "certificateId": null
      },
    ]
  ],
  initExamInfo: {
    beginTime: DLD,
    classId: "",
    classesName: DLS,
    createBy: DLS,
    duration: 60,
    endTime: DLD,
    id: "",
    name: DLS,
    passStatus: null,
    questionCount: 100,
    score: null,
    status: "1",
    passScore: 0,
    totalScore: 100,
    type: "1",
    updateBy: "",
    updateTime: DLD,
    userId: "",
  },
  initShopExam: {
    content: DLS,
    duration: 60,
    eachScore: 1,
    examEndTime: 30,
    examStartTime: 15,
    id: "",
    indep: "1",
    isFree: "1",
    name: DLS,
    passScore: 1,
    price: 0.01,
    proportion: [],
    questionNum: 100,
    reserveEndTime: 10,
    reserveStartTime: 1,
    tenantId: "1",
    totalScore: 100,
    type: "1",
  },
  initLearnClassList: [{
    text: '暂无报名班级',
    value: '0',
  }],
  initActivity: {
    classesList: [],
    content: "",
    id: "",
    name: "",
    url: ""
  },
  initLearnClassValue: '0',
  personCategoryList: [
    {
      label: '全部班级',
      value: '0',
      icon: "apps-o",
      background: 'from-blue-500 bg-gradient-to-r to-blue-400'
    },
    {
      label: '管理人员',
      value: '1553965194246406145',
      icon: "contact",
      background: 'from-yellow-500 bg-gradient-to-r to-yellow-400'
    },
    {
      label: '特种作业人员',
      value: '1551789233782439938',
      icon: "warn-o",
      background: 'from-red-500 bg-gradient-to-r to-red-400'
    }
  ],
  defaultRouteDetail
}
